# Disable Style/Documentation cop
Style/Documentation:
  Enabled: false

# Exclude directories and files from RuboCop
AllCops:
  Exclude:
    - 'lib/fyber/**/*'  # Exclude the 'fyber' directory and all its contents
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
